import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { app } from 'electron';
import { steamService } from './steamService';
import { metadataService } from './metadataService';
import { luaGameService } from './luaGameService';
import { manifestDownloadService } from './manifestDownloadService';
import { licenseClientService } from './licenseClientService';
import { SteamGame, LuaGameInfo } from '../../types';

export class OSTService {
  /**
   * 部署 OpenSteamTool 64 位核心 DLL 三件套到 Steam 根目录
   */
  public async deployCoreBinaries(steamPath: string): Promise<{ success: boolean; deployedCount: number; message: string }> {
    let deployedCount = 0;

    let baseDir = process.cwd();
    try {
      if (typeof __dirname !== 'undefined') {
        baseDir = __dirname;
      } else if (import.meta && import.meta.url) {
        baseDir = path.dirname(fileURLToPath(import.meta.url));
      }
    } catch {
      baseDir = process.cwd();
    }

    const appPath = typeof app !== 'undefined' && app && typeof app.getAppPath === 'function' ? app.getAppPath() : process.cwd();
    const resourcesPath = (process as any).resourcesPath || '';

    // 1. 查找内置资源目录 (兼容开发环境、构建环境及生产打包环境)
    const candidateAssetDirs = [
      path.join(appPath, 'src/main/assets/opensteam'),
      path.join(appPath, 'assets/opensteam'),
      path.join(resourcesPath, 'assets/opensteam'),
      path.join(resourcesPath, 'opensteam'),
      path.join(baseDir, '../src/main/assets/opensteam'),
      path.join(baseDir, '../../src/main/assets/opensteam'),
      path.join(baseDir, '../assets/opensteam'),
      path.join(baseDir, 'assets/opensteam'),
      path.join(process.cwd(), 'src/main/assets/opensteam'),
      path.join(process.cwd(), 'assets/opensteam'),
      path.join(process.cwd(), 'server/data/OpenSteamTool-Release'),
      path.join(appPath, 'server/data/OpenSteamTool-Release')
    ];

    let foundAssetDir: string | null = null;
    for (const d of candidateAssetDirs) {
      if (fs.existsSync(d) && fs.existsSync(path.join(d, 'OpenSteamTool.dll'))) {
        foundAssetDir = d;
        break;
      }
    }

    if (!foundAssetDir) {
      return {
        success: false,
        deployedCount: 0,
        message: '未找到 OpenSteamTool 内核资源文件目录。'
      };
    }

    // 1.5 如果 Steam 正在运行，先确保关闭以释放可能已被 steam.exe 占用的 DLL 文件句柄
    const isRunning = await steamService.isSteamRunning();
    if (isRunning) {
      console.log('[OSTService] 检测到 Steam 正在运行，正在先关闭 Steam 释放文件句柄...');
      await steamService.killSteam();
      await new Promise((resolve) => setTimeout(resolve, 1500));
    }

    // 2. 部署 3 个 64 位核心 DLL (OpenSteamTool.dll, dwmapi.dll, xinput1_4.dll)
    const requiredDlls = ['OpenSteamTool.dll', 'dwmapi.dll', 'xinput1_4.dll'];
    for (const dll of requiredDlls) {
      const srcFile = path.join(foundAssetDir, dll);
      const destFile = path.join(steamPath, dll);
      if (fs.existsSync(srcFile)) {
        try {
          if (fs.existsSync(destFile)) {
            try { fs.chmodSync(destFile, 0o666); } catch {}
          }
          fs.copyFileSync(srcFile, destFile);
          deployedCount++;
          console.log(`[OSTService] 成功部署模块: ${dll} -> ${destFile}`);
        } catch (e: any) {
          console.error(`[OSTService] 复制 ${dll} 到 Steam 失败:`, e.message);
        }
      }
    }

    // 3. 清理可能遗留的旧版冲突 DLL (version.dll, hid.dll)
    const obsoleteDlls = ['version.dll', 'hid.dll'];
    for (const dll of obsoleteDlls) {
      const target = path.join(steamPath, dll);
      if (fs.existsSync(target)) {
        try {
          fs.unlinkSync(target);
        } catch {}
      }
    }

    // 4. 创建 config/lua、st_scripts 与 depotcache 目录，并生成 opensteamtool.toml
    luaGameService.ensureLuaDir(steamPath);
    manifestDownloadService.ensureDepotCacheDir(steamPath);
    const legacyDir = path.join(steamPath, 'st_scripts');
    if (!fs.existsSync(legacyDir)) {
      try { fs.mkdirSync(legacyDir, { recursive: true }); } catch {}
    }
    this.generateTomlConfig(steamPath);

    const isSuccess = deployedCount >= 2;
    return {
      success: isSuccess,
      deployedCount,
      message: isSuccess
        ? `已成功为 Steam 部署 OpenSteamTool 核心组件 (${deployedCount}/3 个模块)、配置文件及 Lua 规则环境！`
        : `部署 OpenSteamTool 核心组件失败 (${deployedCount}/3 个模块)。原因：文件可能被占用或权限不足，请先退出 Steam 客户端后再重试！`
    };
  }

  /**
   * 生成 / 更新 opensteamtool.toml 配置文件
   */
  public generateTomlConfig(steamPath: string, manifestApi: string = 'steamrun'): void {
    const tomlPath = path.join(steamPath, 'opensteamtool.toml');
    const content = `# OpenSteamTool Configuration generated by 春风渡
[inject]
enabled = true

[manifest]
server = "${manifestApi || 'steamrun'}"
`;
    try {
      fs.writeFileSync(tomlPath, content, 'utf-8');
      console.log(`[OSTService] 配置文件 opensteamtool.toml 已生成: ${tomlPath}`);
    } catch (e: any) {
      console.error(`[OSTService] 写入 opensteamtool.toml 失败:`, e.message);
    }
  }

  /**
   * 确保 OpenSteamTool 运行环境完备（仅在激活注入或手动修复时调用）
   */
  public async ensureOSTEnvironment(
    _manifestApi: string = 'steamrun',
    _customApiUrl?: string,
    _enableInject: boolean = true
  ): Promise<{ success: boolean; message: string }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 安装路径，请先在设置中手动指定。' };
    }

    try {
      this.generateTomlConfig(steamPath, _manifestApi);
      const deployRes = await this.deployCoreBinaries(steamPath);
      if (!deployRes.success) {
        return { success: false, message: deployRes.message };
      }

      return {
        success: true,
        message: 'OpenSteamTool 配置文件与运行环境已成功就绪！'
      };
    } catch (e: any) {
      return { success: false, message: `配置 OST 环境失败: ${e.message}` };
    }
  }

  /**
   * 一键激活注入：部署 DLL 并重启 Steam
   */
  public async activateInjection(
    manifestApi: string = 'steamrun',
    customApiUrl?: string,
    shouldRestartSteam: boolean = true
  ): Promise<{ success: boolean; message: string; steamPath?: string; steamRestarted?: boolean }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 安装路径，请先定位 Steam 目录。' };
    }

    // 1. 若 Steam 正在运行，先确保关闭以防 DLL 锁死
    const isRunning = await steamService.isSteamRunning();
    if (isRunning) {
      await steamService.killSteam();
      await new Promise((resolve) => setTimeout(resolve, 1500));
    }

    // 2. 部署核心 DLL 与规则环境
    const envRes = await this.ensureOSTEnvironment(manifestApi, customApiUrl, true);
    if (!envRes.success) {
      return { success: false, message: envRes.message, steamPath };
    }

    // 3. 重新拉起 Steam 客户端
    let steamRestarted = false;
    if (shouldRestartSteam) {
      try {
        await steamService.launchSteam();
        steamRestarted = true;
      } catch (err: any) {
        console.warn('[OSTService] 自动重启 Steam 失败:', err);
      }
    }

    return {
      success: true,
      message: steamRestarted
        ? '已成功为 Steam 安装 OpenSteamTool 核心并自动重启生效！'
        : '已成功为 Steam 安装就绪 OpenSteamTool 核心！',
      steamPath,
      steamRestarted
    };
  }

  /**
   * 卸载 OpenSteamTool 注入组件
   */
  public async uninstallInjection(): Promise<{ success: boolean; message: string }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 安装路径' };
    }

    const dllsToRemove = ['OpenSteamTool.dll', 'dwmapi.dll', 'xinput1_4.dll', 'version.dll', 'hid.dll'];
    for (const dll of dllsToRemove) {
      const p = path.join(steamPath, dll);
      if (fs.existsSync(p)) {
        try { fs.unlinkSync(p); } catch {}
      }
    }

    // 清理日志
    const logDir = path.join(steamPath, 'opensteamtool');
    if (fs.existsSync(logDir)) {
      try {
        fs.rmSync(logDir, { recursive: true, force: true });
      } catch {}
    }

    return {
      success: true,
      message: '已成功移除 OpenSteamTool 注入文件与日志缓存。'
    };
  }

  /**
   * 一键入库：解析完整元数据 -> 写入标准 Lua 规则 (<steam>/config/lua/<appid>.lua)
   * 注意：入库仅写入 Lua 规则与预备目录，绝不杀掉 Steam 进程，实现秒级免重启热生效！
   */
  public async unlockGame(game: SteamGame): Promise<{
    success: boolean;
    message: string;
    scriptPath?: string;
    matchedKeysCount?: number;
    manifestCount?: number;
    notActivated?: boolean;
  }> {
    // 0. 严格校验软件授权状态：未激活时拒绝入库，防止误导用户产生空入库规则
    const license = await licenseClientService.getLicenseInfo(false);
    if (!license || !license.isActivated) {
      return {
        success: false,
        message: '当前设备尚未激活软件授权！无法获取云端 28.8万条解密密钥与游戏入库规则。请先输入卡密激活后再使用。',
        notActivated: true
      };
    }

    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 客户端路径' };
    }

    // 1. 确保规则目录与分包缓存目录存在（无需重装 DLL，无需杀死 Steam 进程）
    luaGameService.ensureLuaDir(steamPath);
    manifestDownloadService.ensureDepotCacheDir(steamPath);

    // 2. 获取包含真实 Depots、DLC Depots、Sudama 密钥和 Token 的完整元数据（多重降级）
    const metadata = await metadataService.fetchMetadata(game.appId, game.nameZh || game.name);

    // 3. 严格遵循规范生成 <SteamPath>/config/lua/<appid>.lua
    const saveRes = luaGameService.saveLuaScript(steamPath, metadata);
    if (!saveRes.success) {
      return { success: false, message: saveRes.message };
    }

    // 4. 统计匹配到的有效解密密钥
    const keysCount = metadata.depots.filter(d => d.depotKey).length;

    // 5. 异步/非阻塞尝试预缓存 Manifest（清单由 OpenSteamTool DLL 运行时通过云端动态下发）
    let manifestCount = 0;
    try {
      const manifestRes = await manifestDownloadService.downloadDepotManifests(
        steamPath,
        game.appId,
        metadata.depots
      );
      manifestCount = manifestRes.downloadedCount;
    } catch (e: any) {
      console.warn('[OSTService] 预缓存分包清单提示 (DLL 运行时将自动下载):', e.message);
    }

    const manifestMsg = manifestCount > 0
      ? `，已就绪 ${manifestCount} 个分包清单 (.manifest)`
      : ` (OpenSteamTool 动态清单就绪)`;

    return {
      success: true,
      message: `成功为「${metadata.name}」写入标准入库规则！已匹配 ${keysCount} 个分包密钥${manifestMsg}！`,
      scriptPath: saveRes.filePath,
      matchedKeysCount: keysCount,
      manifestCount
    };
  }

  /**
   * 兼容旧接口：生成 Lua 脚本
   */
  public async generateLuaScript(game: SteamGame) {
    return this.unlockGame(game);
  }

  /**
   * 获取所有已入库的 AppID 列表
   */
  public async getUnlockedAppIds(): Promise<number[]> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) return [];

    const games = luaGameService.scanUnlockedGames(steamPath);
    return games.map(g => g.appId);
  }

  /**
   * 获取所有已入库游戏的详细信息（包含游戏名称、Depot 数量等）
   */
  public async getUnlockedGames(): Promise<LuaGameInfo[]> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) return [];

    return luaGameService.scanUnlockedGames(steamPath);
  }

  /**
   * 删除指定 AppID 的入库规则（一键出库）
   */
  public async removeUnlockedGame(appId: number | string): Promise<{ success: boolean; message: string }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 路径' };
    }

    return luaGameService.removeLuaScript(steamPath, appId);
  }

  /**
   * 清空所有入库规则
   */
  public async clearAllScripts(): Promise<{ success: boolean; message: string; count: number }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 路径', count: 0 };
    }

    return luaGameService.clearAll(steamPath);
  }
}

export const ostService = new OSTService();

