import fs from 'fs';
import path from 'path';
import axios from 'axios';
import { steamService } from './steamService';
import { SteamGame } from '../../types';
import { APP_CONFIG } from '../../config/appConfig';

export class OSTService {
  /**
   * 确保 st_scripts 目录与 opensteamtool.toml 存在
   */
  public async ensureOSTEnvironment(manifestApi: string = 'opensteamtool', customApiUrl?: string, enableInject: boolean = true): Promise<{ success: boolean; message: string }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 安装路径，请先在设置中手动指定。' };
    }

    try {
      const scriptsDir = path.join(steamPath, 'st_scripts');
      if (!fs.existsSync(scriptsDir)) {
        fs.mkdirSync(scriptsDir, { recursive: true });
      }

      // 生成/更新 opensteamtool.toml 配置文件
      const tomlPath = path.join(steamPath, 'opensteamtool.toml');
      let apiEndpoint = 'https://manifest.opensteamtool.com';
      if (manifestApi === 'steamrun') {
        apiEndpoint = 'https://manifest.steam.run';
      } else if (manifestApi === 'wudrm') {
        apiEndpoint = 'https://gmrc.wudrm.com';
      } else if (manifestApi === 'custom' && customApiUrl) {
        apiEndpoint = customApiUrl;
      }

      const tomlContent = `# OpenSteamTool Configuration generated by SteamMaster
[manifest]
endpoint = "${apiEndpoint}"
auto_download = true

[stats]
enable_api = true

[inject]
enabled = ${enableInject ? 'true' : 'false'}
`;
      fs.writeFileSync(tomlPath, tomlContent, 'utf-8');

      // 确保核心注入 Hook 模块 (如 version.bak.dll 恢复为 version.dll)
      const versionBak = path.join(steamPath, 'version.bak.dll');
      const versionDll = path.join(steamPath, 'version.dll');
      if (fs.existsSync(versionBak) && !fs.existsSync(versionDll)) {
        try {
          fs.copyFileSync(versionBak, versionDll);
        } catch (err: any) {
          console.warn('[OSTService] 恢复 version.dll 失败:', err.message);
        }
      }

      return { success: true, message: 'OpenSteamTool 运行环境配置就绪！' };
    } catch (e: any) {
      return { success: false, message: `配置 OST 环境失败: ${e.message}` };
    }
  }

  /**
   * 启动向导：一键激活 Steam 注入环境
   */
  public async activateInjection(
    manifestApi: string = 'opensteamtool',
    customApiUrl?: string,
    shouldRestartSteam: boolean = true
  ): Promise<{ success: boolean; message: string; steamPath?: string; steamRestarted?: boolean }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 安装路径，请先定位 Steam 目录。' };
    }

    // 1. 初始化并写入环境配置
    const envRes = await this.ensureOSTEnvironment(manifestApi, customApiUrl, true);
    if (!envRes.success) {
      return { success: false, message: envRes.message, steamPath };
    }

    // 2. 自动重启/启动 Steam 客户端以加载注入内核
    let steamRestarted = false;
    if (shouldRestartSteam) {
      try {
        await steamService.restartSteam();
        steamRestarted = true;
      } catch (err: any) {
        console.warn('[OSTService] 自动重启 Steam 失败:', err);
      }
    }

    return {
      success: true,
      message: steamRestarted ? 'Steam 解锁注入环境已成功激活，并已自动重启 Steam！' : 'Steam 解锁注入环境已成功激活！',
      steamPath,
      steamRestarted
    };
  }

  /**
   * 为指定游戏生成一键入库 Lua 脚本并写入 Steam/st_scripts/
   */
  public async generateLuaScript(game: SteamGame): Promise<{ success: boolean; message: string; scriptPath?: string }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 路径' };
    }

    const scriptsDir = path.join(steamPath, 'st_scripts');
    if (!fs.existsSync(scriptsDir)) {
      fs.mkdirSync(scriptsDir, { recursive: true });
    }

    const scriptFile = path.join(scriptsDir, `app_${game.appId}.lua`);
    
    const lines: string[] = [
      `-- SteamMaster 自动生成的入库规则`,
      `-- Game: ${game.nameZh || game.name} (AppID: ${game.appId})`,
      `-- Timestamp: ${new Date().toISOString()}`,
      ``,
      `-- 1. 挂载主游戏本体 (License 伪造)`,
      `addappid(${game.appId}, 1, "0000000000000000000000000000000000000000000000000000000000000000")`,
      ``
    ];

    // 2. 挂载 DLC（如有）
    if (game.dlcs && game.dlcs.length > 0) {
      lines.push(`-- 2. 挂载 DLC 列表`);
      for (const dlcId of game.dlcs) {
        lines.push(`addappid(${dlcId}, 1, "0000000000000000000000000000000000000000000000000000000000000000")`);
      }
      lines.push(``);
    }

    // 3. 聚合密钥：优先通过云端 Node.js 后端拉取 28.8万条 DepotKey 库
    let matchedKeys: { [depotId: string]: string } = { ...(game.depots || {}) };
    try {
      const url = `${APP_CONFIG.API_BASE_URL}/api/depots/${game.appId}`;
      const resp = await axios.get(url, {
        params: { dlcs: game.dlcs?.join(',') },
        timeout: APP_CONFIG.REQUEST_TIMEOUT_MS
      });
      if (resp.data && resp.data.success && resp.data.data) {
        matchedKeys = { ...matchedKeys, ...resp.data.data };
      }
    } catch (e: any) {
      console.warn(`[OSTService] 向云端请求 DepotKey 失败 (${e.message})，使用内置预设密钥`);
    }

    // 写入密钥规则
    if (Object.keys(matchedKeys).length > 0) {
      lines.push(`-- 3. 注入分包解密密钥 (Depot Decryption Keys)`);
      for (const [depotId, key] of Object.entries(matchedKeys)) {
        lines.push(`set_depot_key(${depotId}, "${key}")`);
      }
      lines.push(``);
    }

    try {
      fs.writeFileSync(scriptFile, lines.join('\n'), 'utf-8');
      return {
        success: true,
        message: `成功为「${game.nameZh || game.name}」生成入库规则与密钥！`,
        scriptPath: scriptFile
      };
    } catch (e: any) {
      return { success: false, message: `写入 Lua 脚本失败: ${e.message}` };
    }
  }

  /**
   * 获取所有已入库的 Lua 规则列表
   */
  public async getUnlockedAppIds(): Promise<number[]> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) return [];

    const scriptsDir = path.join(steamPath, 'st_scripts');
    if (!fs.existsSync(scriptsDir)) return [];

    try {
      const files = fs.readdirSync(scriptsDir);
      const appIds: number[] = [];

      for (const file of files) {
        const match = file.match(/app_(\d+)\.lua/i);
        if (match && match[1]) {
          appIds.push(parseInt(match[1], 10));
        }
      }

      return appIds;
    } catch (e) {
      console.error('[OSTService] 读取已入库列表失败:', e);
      return [];
    }
  }

  /**
   * 删除指定 AppID 的 Lua 规则
   */
  public async removeLuaScript(appId: number): Promise<{ success: boolean; message: string }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 路径' };
    }

    const scriptFile = path.join(steamPath, 'st_scripts', `app_${appId}.lua`);
    if (!fs.existsSync(scriptFile)) {
      return { success: true, message: '规则文件已不存在' };
    }

    try {
      fs.unlinkSync(scriptFile);
      return { success: true, message: '成功移除入库规则！请在 Steam 客户端刷新。' };
    } catch (e: any) {
      return { success: false, message: `删除规则文件失败: ${e.message}` };
    }
  }

  public async removeUnlockedGame(appId: number): Promise<{ success: boolean; message: string }> {
    return this.removeLuaScript(appId);
  }

  /**
   * 清空所有入库规则
   */
  public async clearAllScripts(): Promise<{ success: boolean; message: string; count: number }> {
    const steamPath = await steamService.detectSteamPath();
    if (!steamPath) {
      return { success: false, message: '未找到 Steam 路径', count: 0 };
    }

    const scriptsDir = path.join(steamPath, 'st_scripts');
    if (!fs.existsSync(scriptsDir)) {
      return { success: true, message: '规则目录为空', count: 0 };
    }

    try {
      const files = fs.readdirSync(scriptsDir);
      let count = 0;
      for (const file of files) {
        if (file.endsWith('.lua')) {
          fs.unlinkSync(path.join(scriptsDir, file));
          count++;
        }
      }
      return { success: true, message: `已成功清空 ${count} 个游戏的入库规则！`, count };
    } catch (e: any) {
      return { success: false, message: `清空规则失败: ${e.message}`, count: 0 };
    }
  }
}

export const ostService = new OSTService();
