use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};

use crate::steam::is_steam_running;

// 内嵌 OST 核心二进制库（构建时打包进 EXE，零外部依赖）
const OST_DLL: &[u8] = include_bytes!("../assets/opensteam/OpenSteamTool.dll");
const DWMAPI_DLL: &[u8] = include_bytes!("../assets/opensteam/dwmapi.dll");
const XINPUT_DLL: &[u8] = include_bytes!("../assets/opensteam/xinput1_4.dll");

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DepotInfo {
    pub depot_id: u32,
    pub name: Option<String>,
    pub depot_key: Option<String>,
    pub manifest_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnlockGamePayload {
    pub app_id: u32,
    pub name: String,
    pub name_zh: Option<String>,
    pub depots: Option<Vec<DepotInfo>>,
    pub dlcs: Option<Vec<u32>>,
    #[serde(default)]
    pub app_level_key: Option<String>,
    #[serde(default)]
    pub access_token: Option<String>,
    /// 版本锁定开关：true 时写入 setManifestid 钉死当前官方最新 GID（联机对版本用）；
    /// false/缺省不钉，OST 内核每次下载时向官方拉取当时最新清单，永远自动最新版
    #[serde(default)]
    pub lock_version: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClearRulesResult {
    pub removed: usize,
    pub failed: usize,
}

pub fn deploy_core_binaries(steam_path: &Path) -> Result<(), String> {
    // Steam 运行中时核心 DLL 会被进程锁定，覆写必然失败；提前给出可行动的错误信息
    if is_steam_running() {
        return Err("Steam 客户端正在运行，核心 DLL 被进程锁定无法写入。请先退出 Steam（可在工具箱中一键结束进程）后重试。".to_string());
    }

    let targets = [
        ("OpenSteamTool.dll", OST_DLL),
        ("dwmapi.dll", DWMAPI_DLL),
        ("xinput1_4.dll", XINPUT_DLL),
    ];

    for (name, payload) in targets {
        let target = steam_path.join(name);
        fs::write(&target, payload).map_err(|e| {
            if e.kind() == std::io::ErrorKind::PermissionDenied {
                format!("写入 {} 失败: {}（权限不足，Steam 安装在受保护目录时请以管理员身份运行本程序）", name, e)
            } else {
                format!("写入 {} 失败: {}", name, e)
            }
        })?;
    }

    Ok(())
}

pub fn generate_toml_config(steam_path: &Path, manifest_server: &str) -> Result<(), String> {
    let toml_path = steam_path.join("opensteamtool.toml");
    let content = format!(
        "# OpenSteamTool Configuration generated by 春风渡\n\
        [inject]\n\
        enabled = true\n\n\
        [manifest]\n\
        server = \"{}\"\n\
        auto_switch = true\n\
        fallback_servers = [\"gmrc.wudrm.com\", \"manifest.steam.run\", \"opensteamtool.com\"]\n\
        timeout_ms = 4000\n\
        retry_count = 3\n",
        if manifest_server.is_empty() { "steamrun" } else { manifest_server }
    );
    fs::write(toml_path, content).map_err(|e| format!("写入 opensteamtool.toml 失败: {}", e))
}

pub fn ensure_lua_dir(steam_path: &Path) -> Result<PathBuf, String> {
    let lua_dir = steam_path.join("config").join("lua");
    if !lua_dir.exists() {
        fs::create_dir_all(&lua_dir).map_err(|e| format!("创建 Lua 目录失败: {}", e))?;
    }
    let depot_dir = steam_path.join("depotcache");
    if !depot_dir.exists() {
        let _ = fs::create_dir_all(&depot_dir);
    }
    Ok(lua_dir)
}

/// 与 manifests::is_valid_key 保持同一严格标准（长度≥32 且纯 hex 且非全 0）：
/// 两侧标准不一致时，同一密钥在合并阶段与 Lua 生成阶段结论可能不同
fn is_valid_key(key: &str) -> bool {
    key.len() >= 32
        && key.chars().all(|c| c.is_ascii_hexdigit())
        && !key.chars().all(|c| c == '0')
}

/// Lua 字符串字面量转义：游戏名/access_token 来自外部数据，
/// 含引号或换行会破坏 Lua 语法导致整条规则失效
fn lua_escape(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', " ").replace('\r', " ")
}

/// 生成 Lua 入库规则（双方言兼容，最大化内嵌 DLL 版本适配面）：
/// - 密钥同时以 `addappid(id, 1, "key")` 与 `setDepotKey(id, "key")` 双写：
///   第二参数沿用实测可用的 1；setDepotKey 是 37a6d0e 版本验证过可解密的挂载方式
/// - `addtoken` 提供 PICS 访问令牌，`setManifestid` 固定清单 GID
pub fn generate_lua_script(payload: &UnlockGamePayload) -> String {
    let app_id = payload.app_id;
    let name = payload.name_zh.as_deref().unwrap_or(&payload.name);

    let mut lines = Vec::new();
    lines.push(format!("-- Game: {} (AppID: {})", lua_escape(name), app_id));
    lines.push("-- Generated by 春风渡 OST Engine".to_string());

    // 1. 主游戏入库（带 appLevelKey 时以密钥形式挂载）
    match payload.app_level_key.as_deref() {
        Some(k) if is_valid_key(k.trim()) => {
            lines.push(format!("addappid({}, 1, \"{}\")", app_id, k.trim()));
            lines.push(format!("setDepotKey({}, \"{}\")", app_id, k.trim()));
        }
        _ => lines.push(format!("addappid({}, 1)", app_id)),
    }

    // 2. 分包挂载与 Depot 密钥（跳过与本体重复的 depotId）
    let mut seen: Vec<u32> = vec![app_id];
    if let Some(depots) = &payload.depots {
        for depot in depots {
            if seen.contains(&depot.depot_id) {
                continue;
            }
            seen.push(depot.depot_id);
            match depot.depot_key.as_deref() {
                Some(k) if is_valid_key(k.trim()) => {
                    lines.push(format!("addappid({}, 1, \"{}\")", depot.depot_id, k.trim()));
                    lines.push(format!("setDepotKey({}, \"{}\")", depot.depot_id, k.trim()));
                }
                _ => lines.push(format!("addappid({})", depot.depot_id)),
            }
        }
    }

    // 3. PICS Access Token
    if let Some(t) = payload.access_token.as_deref() {
        let t = t.trim();
        if !t.is_empty() && t.chars().all(|c| c.is_ascii_hexdigit()) {
            lines.push(format!("addtoken({}, \"{}\")", app_id, t));
        }
    }

    // 4. DLC 挂载（升序去重，排除本体）
    let mut dlcs: Vec<u32> = payload.dlcs.clone().unwrap_or_default();
    dlcs.retain(|d| *d != app_id);
    dlcs.sort_unstable();
    dlcs.dedup();
    for dlc_id in &dlcs {
        lines.push(format!("addappid({})", dlc_id));
    }

    // 5. 清单 GID 固定（仅版本锁定模式写入）：不钉 GID 时 OST 内核在每次下载时
    // 以注入授权向官方拉取当时最新清单，密钥按 depot 固定跨版本有效，
    // 游戏更新后无须任何手动操作；旧 GID 会被 Valve 从 CDN 回收导致 404，
    // 因此默认不再钉死版本。需要联机对版本时由用户显式开启锁定
    if payload.lock_version == Some(true) {
        if let Some(depots) = &payload.depots {
            for depot in depots {
                if let Some(man) = depot.manifest_id.as_deref() {
                    let man = man.trim();
                    if !man.is_empty() && man != "0" && man.chars().all(|c| c.is_ascii_digit()) {
                        lines.push(format!("setManifestid({}, \"{}\", 0)", depot.depot_id, man));
                    }
                }
            }
        }
    }

    lines.join("\n") + "\n"
}

pub struct SaveRuleResult {
    pub lua_path: PathBuf,
    pub depot_count: usize,
    pub key_count: usize,
    pub manifest_count: usize,
    pub dlc_count: usize,
    pub metadata_ok: bool,
    pub metadata: Option<crate::manifests::AppMetadata>,
    /// 云端元数据获取失败/被拒原因（如未激活、免费额度耗尽）
    pub metadata_message: Option<String>,
}

/// 以服务端元数据为准（密钥库 + SteamCMD 清单 GID + accessToken），与前端传入数据合并
fn merge_with_server_metadata(payload: &UnlockGamePayload) -> (UnlockGamePayload, bool, Option<crate::manifests::AppMetadata>, Option<String>) {
    let mut by_id: std::collections::BTreeMap<u32, DepotInfo> = std::collections::BTreeMap::new();
    for d in payload.depots.iter().flatten() {
        by_id.entry(d.depot_id).or_insert_with(|| d.clone());
    }
    let mut dlcs: Vec<u32> = payload.dlcs.clone().unwrap_or_default();
    let mut app_level_key = payload.app_level_key.clone();
    let mut access_token = payload.access_token.clone();
    let mut metadata_ok = false;
    let mut metadata = None;
    let mut metadata_message: Option<String> = None;

    match crate::manifests::parse_metadata(payload.app_id) {
        Ok(meta) => {
            metadata_ok = true;
            for m in &meta.depots {
                let id: u32 = match m.depot_id.parse() {
                    Ok(v) if v > 0 => v,
                    _ => continue,
                };
                let entry = by_id.entry(id).or_insert_with(|| DepotInfo {
                    depot_id: id,
                    name: None,
                    depot_key: None,
                    manifest_id: None,
                });
                if let Some(g) = &m.manifest_gid {
                    if !g.is_empty() && g != "0" {
                        entry.manifest_id = Some(g.clone());
                    }
                }
                if let Some(k) = &m.depot_key {
                    if is_valid_key(k) {
                        entry.depot_key = Some(k.clone());
                    }
                }
            }
            for dlc in &meta.dlc_ids {
                if *dlc != payload.app_id && !dlcs.contains(dlc) {
                    dlcs.push(*dlc);
                }
            }
            // 服务端 appLevelKey 优先（绝不使用全 0 占位符）
            if let Some(k) = &meta.app_level_key {
                if is_valid_key(k) {
                    app_level_key = Some(k.clone());
                }
            }
            if let Some(t) = &meta.access_token {
                if !t.is_empty() {
                    access_token = Some(t.clone());
                }
            }
            metadata = Some(meta);
        }
        Err(e) => {
            // 记录云端拒绝/失败原因（如免费额度耗尽），随结果透传给前端提示
            metadata_message = Some(e);
        }
    }

    let merged = UnlockGamePayload {
        app_id: payload.app_id,
        name: payload.name.clone(),
        name_zh: payload.name_zh.clone(),
        depots: Some(by_id.into_values().collect()),
        dlcs: Some(dlcs),
        app_level_key,
        access_token,
        lock_version: payload.lock_version,
    };
    (merged, metadata_ok, metadata, metadata_message)
}

pub fn save_lua_rule(steam_path: &Path, payload: &UnlockGamePayload) -> Result<SaveRuleResult, String> {
    let (merged, metadata_ok, metadata, metadata_message) = merge_with_server_metadata(payload);
    let key_count = merged
        .depots
        .iter()
        .flatten()
        .filter(|d| d.depot_key.as_deref().map(|k| is_valid_key(k.trim())).unwrap_or(false))
        .count()
        + merged
            .app_level_key
            .as_deref()
            .map(|k| is_valid_key(k.trim()))
            .unwrap_or(false) as usize;
    let manifest_count = merged
        .depots
        .iter()
        .flatten()
        .filter(|d| {
            d.manifest_id
                .as_deref()
                .map(|m| !m.trim().is_empty() && m.trim() != "0")
                .unwrap_or(false)
        })
        .count();
    let depot_count = merged.depots.as_ref().map(|d| d.len()).unwrap_or(0);
    let dlc_count = merged.dlcs.as_ref().map(|d| d.len()).unwrap_or(0);

    let lua_dir = ensure_lua_dir(steam_path)?;
    let lua_file = lua_dir.join(format!("{}.lua", payload.app_id));
    let content = generate_lua_script(&merged);
    fs::write(&lua_file, &content).map_err(|e| format!("写入 Lua 规则失败: {}", e))?;

    // 双轨兼容：镜像到 st_scripts/（旧模式目录）
    let legacy_dir = steam_path.join("st_scripts");
    if !legacy_dir.exists() {
        let _ = fs::create_dir_all(&legacy_dir);
    }
    let _ = fs::write(legacy_dir.join(format!("{}.lua", payload.app_id)), &content);

    // GreenLuma (AppList) 双轨同步
    sync_greenluma_app_list(steam_path);

    Ok(SaveRuleResult {
        lua_path: lua_file,
        depot_count,
        key_count,
        manifest_count,
        dlc_count,
        metadata_ok,
        metadata,
        metadata_message,
    })
}

/// 扫描一行中的 `addappid(<digits>` 提取 AppID（纯字节级扫描，中文注释行安全）
fn extract_addappid_ids(content: &str) -> Vec<u32> {
    const NEEDLE: &[u8] = b"addappid";
    let bytes = content.as_bytes();
    let mut ids = Vec::new();
    let mut i = 0;
    while i + NEEDLE.len() <= bytes.len() {
        if bytes[i..i + NEEDLE.len()].eq_ignore_ascii_case(NEEDLE) {
            let mut j = i + NEEDLE.len();
            while j < bytes.len() && bytes[j].is_ascii_whitespace() {
                j += 1;
            }
            if j < bytes.len() && bytes[j] == b'(' {
                j += 1;
                let start = j;
                while j < bytes.len() && bytes[j].is_ascii_digit() {
                    j += 1;
                }
                if j > start {
                    if let Ok(id) = content[start..j].parse::<u32>() {
                        ids.push(id);
                    }
                }
            }
        }
        i += 1;
    }
    ids
}

/// 判断 Lua 内容中是否含有效 Depot 密钥（32 位以上非全 0 hex，兼容新旧两种方言）
pub fn lua_has_valid_key(content: &str) -> bool {
    for line in content.lines() {
        let lower = line.to_ascii_lowercase();
        if !lower.contains("addappid") && !lower.contains("setdepotkey") {
            continue;
        }
        if let Some(start) = line.find('"') {
            if let Some(end) = line[start + 1..].find('"') {
                let key = &line[start + 1..start + 1 + end];
                if is_valid_key(key.trim()) {
                    return true;
                }
            }
        }
    }
    false
}

/// 双轨兼容：将全部已入库 AppID（本体/DLC/Depot）同步到 GreenLuma AppList 目录。
/// 仅清理本工具通过 .cfd_managed.json 写入的文件，用户手动维护的条目不受影响。
pub fn sync_greenluma_app_list(steam_path: &Path) {
    let app_list_dir = steam_path.join("AppList");
    if !app_list_dir.exists() {
        let _ = fs::create_dir_all(&app_list_dir);
    }
    let lua_dir = steam_path.join("config").join("lua");

    let mut all_ids: Vec<u32> = Vec::new();
    if let Ok(entries) = fs::read_dir(&lua_dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            let Ok(id) = stem.parse::<u32>() else {
                continue;
            };
            if path.extension().and_then(|e| e.to_str()).map(|e| e.eq_ignore_ascii_case("lua")) != Some(true) {
                continue;
            }
            if !all_ids.contains(&id) {
                all_ids.push(id);
            }
            if let Ok(content) = fs::read_to_string(&path) {
                for id in extract_addappid_ids(&content) {
                    if !all_ids.contains(&id) {
                        all_ids.push(id);
                    }
                }
            }
        }
    }
    all_ids.sort_unstable();
    all_ids.dedup();

    // 清理此前由本工具写入的 AppList 文件
    let managed_file = app_list_dir.join(".cfd_managed.json");
    if let Ok(text) = fs::read_to_string(&managed_file) {
        if let Ok(list) = serde_json::from_str::<Vec<String>>(&text) {
            for name in list {
                let _ = fs::remove_file(app_list_dir.join(name));
            }
        }
    }

    let written: Vec<String> = all_ids
        .iter()
        .enumerate()
        .map(|(idx, id)| {
            let name = format!("{}.txt", idx);
            let _ = fs::write(app_list_dir.join(&name), id.to_string());
            name
        })
        .collect();
    let _ = fs::write(&managed_file, serde_json::to_string_pretty(&written).unwrap_or_default());
}

pub fn get_unlocked_app_ids(steam_path: &Path) -> Vec<u32> {
    let lua_dir = steam_path.join("config").join("lua");
    if !lua_dir.exists() {
        return Vec::new();
    }

    let mut ids = Vec::new();
    if let Ok(entries) = fs::read_dir(lua_dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.extension().map(|e| e == "lua").unwrap_or(false) {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    if let Ok(id) = stem.parse::<u32>() {
                        ids.push(id);
                    }
                }
            }
        }
    }
    ids
}

pub fn remove_unlocked_rule(steam_path: &Path, app_id: u32) -> Result<(), String> {
    // 与 Electron 版 removeLuaScript 一致：清理全部 4 处规则落点
    let paths = [
        steam_path.join("config").join("lua").join(format!("{}.lua", app_id)),
        steam_path.join("st_scripts").join(format!("{}.lua", app_id)),
        steam_path.join("st_scripts").join(format!("app_{}.lua", app_id)),
        steam_path.join("config").join("stplug-in").join(format!("app_{}.lua", app_id)),
    ];
    let mut removed = false;
    for p in paths {
        if p.exists() && fs::remove_file(&p).is_ok() {
            removed = true;
        }
    }
    let _ = removed;
    sync_greenluma_app_list(steam_path);
    Ok(())
}

pub fn clear_all_rules(steam_path: &Path) -> Result<ClearRulesResult, String> {
    let dirs = [
        steam_path.join("config").join("lua"),
        steam_path.join("st_scripts"),
        steam_path.join("config").join("stplug-in"),
    ];
    let mut removed = 0;
    let mut failed = 0;
    for dir in dirs {
        if !dir.exists() {
            continue;
        }
        if let Ok(entries) = fs::read_dir(&dir) {
            for entry in entries.filter_map(|e| e.ok()) {
                let p = entry.path();
                if p.extension().map(|e| e == "lua").unwrap_or(false) {
                    if fs::remove_file(&p).is_ok() {
                        removed += 1;
                    } else {
                        failed += 1;
                    }
                }
            }
        }
    }
    sync_greenluma_app_list(steam_path);
    Ok(ClearRulesResult { removed, failed })
}

pub fn uninstall_injection_files(steam_path: &Path) -> Result<Vec<String>, String> {
    let files = [
        "OpenSteamTool.dll",
        "dwmapi.dll",
        "xinput1_4.dll",
        "opensteamtool.toml",
    ];
    let mut failed = Vec::new();
    for file_name in files {
        let p = steam_path.join(file_name);
        if p.exists() {
            if let Err(e) = fs::remove_file(&p) {
                failed.push(format!("{}: {}（可能被正在运行的 Steam 锁定）", file_name, e));
            }
        }
    }
    if failed.is_empty() {
        Ok(Vec::new())
    } else {
        Err(failed.join("; "))
    }
}

// ==================== 游戏版本更新检测 ====================

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DepotGidChange {
    pub depot_id: u32,
    pub old_gid: Option<String>,
    pub new_gid: String,
}

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GameUpdateStatus {
    pub app_id: u32,
    /// 是否成功取到云端实时元数据；false 时 hasUpdate 无意义，message 给出原因
    pub checked: bool,
    /// Lua 规则是否钉死了清单版本（setManifestid）。false = 跟随官方最新版，
    /// 每次下载自动拉取当时最新清单，不存在"落后"一说
    pub pinned: bool,
    pub has_update: bool,
    pub changed_depots: Vec<DepotGidChange>,
    pub message: Option<String>,
}

/// 从 Lua 规则文本中提取 `setManifestid(depot, "gid", 0)` 固定的清单 GID
pub fn extract_manifest_gids(lua_content: &str) -> Vec<(u32, String)> {
    let mut out = Vec::new();
    for line in lua_content.lines() {
        let t = line.trim();
        if !(t.starts_with("setManifestid(") || t.starts_with("setManifestId(")) {
            continue;
        }
        let inner = match (t.find('('), t.rfind(')')) {
            (Some(a), Some(b)) if b > a => &t[a + 1..b],
            _ => continue,
        };
        let parts: Vec<&str> = inner.split(',').collect();
        if parts.len() < 2 {
            continue;
        }
        let depot: u32 = match parts[0].trim().parse() {
            Ok(v) => v,
            Err(_) => continue,
        };
        let gid = parts[1].trim().trim_matches('"').trim();
        if !gid.is_empty() && gid != "0" && gid.chars().all(|c| c.is_ascii_digit()) {
            out.push((depot, gid.to_string()));
        }
    }
    out
}

/// 对比单个游戏 Lua 规则中钉死的 GID 与云端实时元数据。
/// 必须在 spawn_blocking 线程调用（parse_metadata 内部有阻塞 IO）。
pub fn check_game_update_status(steam_path: &Path, app_id: u32) -> GameUpdateStatus {
    let lua_path = steam_path.join("config").join("lua").join(format!("{}.lua", app_id));
    let old_map: std::collections::BTreeMap<u32, String> = std::fs::read_to_string(&lua_path)
        .map(|c| extract_manifest_gids(&c).into_iter().collect())
        .unwrap_or_default();

    // 未钉版本的规则 = 跟随官方最新版，无须查询云端即可下结论
    if old_map.is_empty() {
        return GameUpdateStatus {
            app_id,
            checked: true,
            pinned: false,
            has_update: false,
            changed_depots: Vec::new(),
            message: None,
        };
    }

    match crate::manifests::parse_metadata(app_id) {
        Ok(meta) => {
            let mut changed = Vec::new();
            for d in &meta.depots {
                let Some(g) = d.manifest_gid.as_deref().map(str::trim) else { continue };
                if g.is_empty() || g == "0" || !g.chars().all(|c| c.is_ascii_digit()) {
                    continue;
                }
                let Ok(id) = d.depot_id.parse::<u32>() else { continue };
                if id == 0 {
                    continue;
                }
                match old_map.get(&id) {
                    Some(old) if old == g => {}
                    // 旧规则缺失该 depot 的 GID（如入库时服务端无数据）也视为可更新补全
                    old => changed.push(DepotGidChange {
                        depot_id: id,
                        old_gid: old.cloned(),
                        new_gid: g.to_string(),
                    }),
                }
            }
            GameUpdateStatus {
                app_id,
                checked: true,
                pinned: true,
                has_update: !changed.is_empty(),
                changed_depots: changed,
                message: None,
            }
        }
        Err(e) => GameUpdateStatus {
            app_id,
            checked: false,
            pinned: true,
            has_update: false,
            changed_depots: Vec::new(),
            message: Some(e),
        },
    }
}

// ==================== OST 内核在线同步 ====================
// OpenSteamTool 内核在 GitHub 发布（OpenSteam001/OpenSteamTool），
// 内嵌 DLL 只是首次安装种子；本模块在运行时从官方 release 拉取最新版
// 覆盖部署到 Steam 目录（与 deploy_core_binaries 同一套写入目标），
// 使用户不必等春风渡发版就能用上内核修复与新特性。

pub const OST_REPO: &str = "OpenSteam001/OpenSteamTool";
const OST_META_FILE: &str = "opensteamtool_meta.json";
// 打包时内嵌的内核种子：经字节级比对确认与官方 1.4.8 Debug 构建完全一致。
// Debug 构建无版本资源信息且体积大（12MB vs Release 1.4MB），同步会升级为 Release
const EMBEDDED_OST_TAG: &str = "1.4.8 (Debug 构建)";

#[derive(Debug, Clone, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OstSyncInfo {
    /// 已部署版本：meta 文件记录的 tag；从未在线同步过则为 "内置版本"
    pub current_tag: String,
    pub latest_tag: Option<String>,
    pub published_at: Option<String>,
    pub update_available: bool,
    pub steam_running: bool,
    pub message: Option<String>,
}

fn read_deployed_ost_tag(steam_path: &Path) -> String {
    std::fs::read_to_string(steam_path.join(OST_META_FILE))
        .ok()
        .and_then(|s| serde_json::from_str::<serde_json::Value>(&s).ok())
        .and_then(|v| v.get("tag").and_then(|t| t.as_str()).map(|s| s.to_string()))
        .unwrap_or_else(|| EMBEDDED_OST_TAG.to_string())
}

fn write_deployed_ost_tag(steam_path: &Path, tag: &str) {
    let meta = serde_json::json!({
        "tag": tag,
        "syncedAt": std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs())
            .unwrap_or(0)
    });
    let _ = std::fs::write(steam_path.join(OST_META_FILE), meta.to_string());
}

/// 查询 OST 最新 release（tag + Release.zip 资产名）。
/// api.github.com 直连失败时回退解析 github.com releases/latest 的重定向地址
fn fetch_latest_ost_release() -> Result<(String, Option<String>, String), String> {
    let api_url = format!("https://api.github.com/repos/{}/releases/latest", OST_REPO);
    if let Ok(resp) = crate::manifests::block_on(
        crate::manifests::http_client()
            .get(&api_url)
            .timeout(std::time::Duration::from_secs(10))
            .header("User-Agent", "chunfengdu")
            .header("Accept", "application/vnd.github+json")
            .send(),
    ) {
        if let Ok(json) = crate::manifests::block_on(resp.json::<serde_json::Value>()) {
            if let Some(tag) = json.get("tag_name").and_then(|t| t.as_str()) {
                let published = json
                    .get("published_at")
                    .and_then(|p| p.as_str())
                    .map(|s| s.to_string());
                // 优先取体积小的 Release 包（Debug 包 28MB 且非分发用途）
                let asset = json
                    .get("assets")
                    .and_then(|a| a.as_array())
                    .and_then(|list| {
                        list.iter()
                            .filter_map(|a| a.get("name").and_then(|n| n.as_str()))
                            .find(|n| n.contains("Release.zip") && !n.contains("Debug"))
                            .or_else(|| list.iter().filter_map(|a| a.get("name").and_then(|n| n.as_str())).find(|n| n.ends_with(".zip")))
                    })
                    .map(|s| s.to_string());
                if let Some(asset) = asset {
                    return Ok((tag.to_string(), published, asset));
                }
            }
        }
    }

    // 回退：releases/latest 302 重定向的 Location 末段即 tag
    let redirect_url = format!("https://github.com/{}/releases/latest", OST_REPO);
    let no_redirect = crate::manifests::http_client_builder()
        .redirect(reqwest::redirect::Policy::none())
        .build()
        .map_err(|e| format!("初始化 HTTP 客户端失败: {}", e))?;
    if let Ok(resp) = crate::manifests::block_on(
        no_redirect
            .get(&redirect_url)
            .timeout(std::time::Duration::from_secs(10))
            .header("User-Agent", "chunfengdu")
            .send(),
    ) {
        if let Some(loc) = resp
            .headers()
            .get(reqwest::header::LOCATION)
            .and_then(|l| l.to_str().ok())
        {
            let tag = loc.trim_end_matches('/').rsplit('/').next().unwrap_or("");
            if !tag.is_empty() && tag != "latest" {
                return Ok((
                    tag.to_string(),
                    None,
                    format!("OpenSteamTool-{}-Release.zip", tag),
                ));
            }
        }
    }

    // 最终回退：经春风渡服务器中转查询（服务器可达 GitHub，任何客户端网络环境可用）
    let relay_url = format!("{}/api/ost/latest", crate::manifests::SERVER_API);
    if let Ok(resp) = crate::manifests::block_on(
        crate::manifests::http_client()
            .get(&relay_url)
            .timeout(std::time::Duration::from_secs(12))
            .header("User-Agent", "chunfengdu")
            .header("x-device-id", crate::device::get_device_id())
            .send(),
    ) {
        if let Ok(json) = crate::manifests::block_on(resp.json::<serde_json::Value>()) {
            if json.get("success").and_then(|v| v.as_bool()) == Some(true) {
                if let (Some(tag), Some(asset)) = (
                    json.get("tag").and_then(|t| t.as_str()),
                    json.get("asset").and_then(|a| a.as_str()),
                ) {
                    if !tag.is_empty() && !asset.is_empty() {
                        let published = json
                            .get("publishedAt")
                            .and_then(|p| p.as_str())
                            .map(|s| s.to_string());
                        return Ok((tag.to_string(), published, asset.to_string()));
                    }
                }
            }
        }
    }

    Err("无法连接 GitHub 查询最新版本（可检查网络或稍后再试）".to_string())
}

fn ost_release_zip_url(tag: &str, asset: &str) -> String {
    format!("https://github.com/{}/releases/download/{}/{}", OST_REPO, tag, asset)
}

/// 从 release zip 中提取核心三件套（OpenSteamTool.dll / dwmapi.dll / xinput1_4.dll），
/// 校验非空且为合法 PE（MZ 头），其余 .lib/.exp 编译附属物一律忽略
fn extract_ost_core_from_zip(zip_bytes: &[u8]) -> Result<Vec<(&'static str, Vec<u8>)>, String> {
    let mut archive = zip::ZipArchive::new(std::io::Cursor::new(zip_bytes))
        .map_err(|e| format!("release 压缩包解析失败: {}", e))?;
    let wanted = ["OpenSteamTool.dll", "dwmapi.dll", "xinput1_4.dll"];
    let mut out: Vec<(&'static str, Vec<u8>)> = Vec::new();
    for name in wanted {
        let mut found: Option<Vec<u8>> = None;
        for i in 0..archive.len() {
            let mut entry = archive
                .by_index(i)
                .map_err(|e| format!("读取压缩包条目失败: {}", e))?;
            if entry.is_dir() {
                continue;
            }
            let fname = entry.name().rsplit('/').next().unwrap_or("");
            if fname.eq_ignore_ascii_case(name) {
                let mut buf = Vec::with_capacity(entry.size() as usize);
                std::io::Read::read_to_end(&mut entry, &mut buf)
                    .map_err(|e| format!("读取 {} 失败: {}", name, e))?;
                if buf.len() > 1024 && buf.starts_with(b"MZ") {
                    found = Some(buf);
                }
                break;
            }
        }
        out.push((
            name,
            found.ok_or_else(|| format!("release 包中未找到有效的 {}", name))?,
        ));
    }
    Ok(out)
}

/// 从多个镜像链下载 release zip（官方直链 ➔ ghfast.top ➔ gh-proxy.com）
fn download_ost_release_zip(tag: &str, asset: &str) -> Result<Vec<u8>, String> {
    let target = ost_release_zip_url(tag, asset);
    let mirrors = [
        target.clone(),
        format!("https://ghfast.top/{}", target),
        format!("https://gh-proxy.com/{}", target),
        // 最终兜底：经春风渡服务器中转下载（客户端 GitHub 完全不可达时仍可同步）
        format!(
            "{}/api/ost/download/{}/{}",
            crate::manifests::SERVER_API, tag, asset
        ),
    ];
    let mut last_err = String::from("未尝试任何镜像");
    for url in &mirrors {
        match crate::manifests::block_on(
            crate::manifests::http_client()
                .get(url)
                .timeout(std::time::Duration::from_secs(120))
                .header("User-Agent", "chunfengdu")
                .send(),
        ) {
            Ok(resp) if resp.status().is_success() => {
                match crate::manifests::block_on(resp.bytes()) {
                    Ok(bytes) if bytes.len() > 100 * 1024 => return Ok(bytes.to_vec()),
                    Ok(_) => last_err = format!("{} 返回内容异常", url),
                    Err(e) => last_err = format!("{} 下载中断: {}", url, e),
                }
            }
            Ok(resp) => last_err = format!("{} 返回 HTTP {}", url, resp.status()),
            Err(e) => last_err = format!("{} 连接失败: {}", url, e),
        }
    }
    Err(format!("所有镜像均下载失败，最后错误：{}", last_err))
}

/// 检查内核同步状态（当前部署 tag vs GitHub 最新 tag）。须在 spawn_blocking 调用
pub fn check_ost_sync_status(steam_path: &Path) -> OstSyncInfo {
    let current_tag = read_deployed_ost_tag(steam_path);
    let steam_running = is_steam_running();
    match fetch_latest_ost_release() {
        Ok((latest_tag, published_at, _asset)) => OstSyncInfo {
            update_available: latest_tag != current_tag,
            current_tag,
            latest_tag: Some(latest_tag),
            published_at,
            steam_running,
            message: None,
        },
        Err(e) => OstSyncInfo {
            current_tag,
            latest_tag: None,
            published_at: None,
            update_available: false,
            steam_running,
            message: Some(e),
        },
    }
}

/// 在线同步最新内核：下载 release zip、校验三件套、覆盖部署到 Steam 目录并记录版本。
/// 须在 spawn_blocking 调用；Steam 运行中时 DLL 被锁定，必须先退出
pub fn sync_ost_latest(steam_path: &Path) -> Result<String, String> {
    if is_steam_running() {
        return Err("Steam 客户端正在运行，核心 DLL 被锁定无法替换。请先退出 Steam（可在工具箱一键结束进程）后重试。".to_string());
    }

    let (tag, _published, asset) = fetch_latest_ost_release()?;
    let current_tag = read_deployed_ost_tag(steam_path);
    if tag == current_tag {
        return Ok(format!("内核已是最新版本（{}），无需同步。", tag));
    }

    let zip_bytes = download_ost_release_zip(&tag, &asset)?;
    let core = extract_ost_core_from_zip(&zip_bytes)?;

    for (name, bytes) in &core {
        std::fs::write(steam_path.join(name), bytes)
            .map_err(|e| format!("写入 {} 失败: {}（权限不足时请以管理员身份运行本程序）", name, e))?;
    }
    write_deployed_ost_tag(steam_path, &tag);

    Ok(format!(
        "已同步 OpenSteamTool 内核 {} → {}（{} 个核心组件已部署）！重新启动 Steam 后生效。",
        current_tag, tag, core.len()
    ))
}
