use std::fs;
use std::path::{Path, PathBuf};
use serde::{Deserialize, Serialize};

// 内嵌 OST 核心二进制库（构建时打包进 EXE，零外部依赖）
const OST_DLL: &[u8] = include_bytes!("../assets/opensteam/OpenSteamTool.dll");
const DWMAPI_DLL: &[u8] = include_bytes!("../assets/opensteam/dwmapi.dll");
const XINPUT_DLL: &[u8] = include_bytes!("../assets/opensteam/xinput1_4.dll");

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DepotInfo {
    pub depot_id: u32,
    pub name: Option<String>,
    pub depot_key: Option<String>,
    pub manifest_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UnlockGamePayload {
    pub app_id: u32,
    pub name: String,
    pub name_zh: Option<String>,
    pub depots: Option<Vec<DepotInfo>>,
    pub dlcs: Option<Vec<u32>>,
}

pub fn deploy_core_binaries(steam_path: &Path) -> Result<(), String> {
    let ost_target = steam_path.join("OpenSteamTool.dll");
    let dwmapi_target = steam_path.join("dwmapi.dll");
    let xinput_target = steam_path.join("xinput1_4.dll");

    fs::write(&ost_target, OST_DLL)
        .map_err(|e| format!("写入 OpenSteamTool.dll 失败: {}", e))?;
    fs::write(&dwmapi_target, DWMAPI_DLL)
        .map_err(|e| format!("写入 dwmapi.dll 失败: {}", e))?;
    fs::write(&xinput_target, XINPUT_DLL)
        .map_err(|e| format!("写入 xinput1_4.dll 失败: {}", e))?;

    Ok(())
}

pub fn generate_toml_config(steam_path: &Path, manifest_server: &str) -> Result<(), String> {
    let toml_path = steam_path.join("opensteamtool.toml");
    let content = format!(
        "# OpenSteamTool Configuration generated by 春风渡\n\
        [inject]\n\
        enabled = true\n\n\
        [manifest]\n\
        server = \"{}\"\n",
        if manifest_server.is_empty() { "steamrun" } else { manifest_server }
    );
    fs::write(toml_path, content).map_err(|e| format!("写入 opensteamtool.toml 失败: {}", e))
}

pub fn ensure_lua_dir(steam_path: &Path) -> Result<PathBuf, String> {
    let lua_dir = steam_path.join("config").join("lua");
    if !lua_dir.exists() {
        fs::create_dir_all(&lua_dir).map_err(|e| format!("创建 Lua 目录失败: {}", e))?;
    }
    let depot_dir = steam_path.join("depotcache");
    if !depot_dir.exists() {
        let _ = fs::create_dir_all(&depot_dir);
    }
    Ok(lua_dir)
}

pub fn generate_lua_script(payload: &UnlockGamePayload) -> String {
    let app_id = payload.app_id;
    let name = payload.name_zh.as_deref().unwrap_or(&payload.name);

    let mut lines = Vec::new();
    lines.push(format!("-- Game: {} (AppID: {})", name, app_id));
    lines.push(format!("-- Generated by 春风渡 OST Engine"));
    lines.push(format!("addappid({}, 1, \"0000000000000000000000000000000000000000000000000000000000000000\")", app_id));

    if let Some(dlcs) = &payload.dlcs {
        for dlc_id in dlcs {
            if *dlc_id != app_id {
                lines.push(format!("addappid({}, 1, \"0000000000000000000000000000000000000000000000000000000000000000\")", dlc_id));
            }
        }
    }

    if let Some(depots) = &payload.depots {
        for depot in depots {
            if let Some(key) = &depot.depot_key {
                let clean_key = key.trim();
                if !clean_key.is_empty() && clean_key != "0000000000000000000000000000000000000000000000000000000000000000" {
                    lines.push(format!("setDepotKey({}, \"{}\")", depot.depot_id, clean_key));
                }
            }
            if let Some(man) = &depot.manifest_id {
                let clean_man = man.trim();
                if !clean_man.is_empty() && clean_man != "0" {
                    lines.push(format!("setManifestid({}, \"{}\", 0)", depot.depot_id, clean_man));
                }
            }
        }
    }

    lines.join("\n") + "\n"
}

pub fn save_lua_rule(steam_path: &Path, payload: &UnlockGamePayload) -> Result<PathBuf, String> {
    let lua_dir = ensure_lua_dir(steam_path)?;
    let lua_file = lua_dir.join(format!("{}.lua", payload.app_id));
    let content = generate_lua_script(payload);
    fs::write(&lua_file, content).map_err(|e| format!("写入 Lua 规则失败: {}", e))?;
    Ok(lua_file)
}

pub fn get_unlocked_app_ids(steam_path: &Path) -> Vec<u32> {
    let lua_dir = steam_path.join("config").join("lua");
    if !lua_dir.exists() {
        return Vec::new();
    }

    let mut ids = Vec::new();
    if let Ok(entries) = fs::read_dir(lua_dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            if path.extension().map(|e| e == "lua").unwrap_or(false) {
                if let Some(stem) = path.file_stem().and_then(|s| s.to_str()) {
                    if let Ok(id) = stem.parse::<u32>() {
                        ids.push(id);
                    }
                }
            }
        }
    }
    ids
}

pub fn remove_unlocked_rule(steam_path: &Path, app_id: u32) -> Result<(), String> {
    let lua_file = steam_path.join("config").join("lua").join(format!("{}.lua", app_id));
    if lua_file.exists() {
        fs::remove_file(&lua_file).map_err(|e| format!("删除规则失败: {}", e))?;
    }
    Ok(())
}

pub fn clear_all_rules(steam_path: &Path) -> Result<usize, String> {
    let lua_dir = steam_path.join("config").join("lua");
    if !lua_dir.exists() {
        return Ok(0);
    }
    let mut count = 0;
    if let Ok(entries) = fs::read_dir(lua_dir) {
        for entry in entries.filter_map(|e| e.ok()) {
            let p = entry.path();
            if p.extension().map(|e| e == "lua").unwrap_or(false) {
                if fs::remove_file(p).is_ok() {
                    count += 1;
                }
            }
        }
    }
    Ok(count)
}

pub fn uninstall_injection_files(steam_path: &Path) -> Result<(), String> {
    let files = [
        "OpenSteamTool.dll",
        "dwmapi.dll",
        "xinput1_4.dll",
        "opensteamtool.toml",
    ];
    for file_name in files {
        let p = steam_path.join(file_name);
        if p.exists() {
            let _ = fs::remove_file(p);
        }
    }
    Ok(())
}
