use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClearRulesResult {
    pub removed: usize,
    pub failed: usize,
    /// 非本工具生成的第三方规则脚本，已跳过保留
    pub skipped: usize,
}

pub fn remove_unlocked_rule(steam_path: &Path, app_id: u32) -> Result<(usize, usize), String> {
    // 与 Electron 版 removeLuaScript 一致：清理全部 4 处规则落点
    let paths = [
        steam_path
            .join("config")
            .join("lua")
            .join(format!("{}.lua", app_id)),
        steam_path
            .join("config")
            .join("lua")
            .join("Disable")
            .join(format!("{}.lua", app_id)),
        steam_path
            .join("st_scripts")
            .join(format!("{}.lua", app_id)),
        steam_path
            .join("st_scripts")
            .join(format!("app_{}.lua", app_id)),
        steam_path
            .join("config")
            .join("stplug-in")
            .join(format!("app_{}.lua", app_id)),
    ];
    let mut removed = 0;
    let mut failed = 0;
    for p in paths {
        if p.exists() {
            if fs::remove_file(&p).is_ok() {
                removed += 1;
            } else {
                failed += 1;
            }
        }
    }
    Ok((removed, failed))
}

const GENERATED_RULE_MARKER: &str = "Generated by 春风渡";

pub fn clear_all_rules(steam_path: &Path) -> Result<ClearRulesResult, String> {
    let dirs = [
        steam_path.join("config").join("lua"),
        steam_path.join("config").join("lua").join("Disable"),
        steam_path.join("st_scripts"),
        steam_path.join("config").join("stplug-in"),
    ];
    let mut removed = 0;
    let mut failed = 0;
    let mut skipped = 0;
    for dir in dirs {
        if !dir.exists() {
            continue;
        }
        if let Ok(entries) = fs::read_dir(&dir) {
            for entry in entries.filter_map(|e| e.ok()) {
                let p = entry.path();
                if p.extension().map(|e| e == "lua").unwrap_or(false) {
                    // 只删除本工具生成的规则：第三方脚本（如内核自带/用户手写）
                    // 不含生成标记，一律跳过保留。读取失败（非 UTF-8/被占用）
                    // 时按无标记处理，宁可漏删不可误删
                    let is_ours = fs::read_to_string(&p)
                        .map(|c| c.contains(GENERATED_RULE_MARKER))
                        .unwrap_or(false);
                    if !is_ours {
                        skipped += 1;
                        continue;
                    }
                    if fs::remove_file(&p).is_ok() {
                        removed += 1;
                    } else {
                        failed += 1;
                    }
                }
            }
        }
    }
    Ok(ClearRulesResult {
        removed,
        failed,
        skipped,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering};
    static SEQUENCE: AtomicUsize = AtomicUsize::new(0);
    fn fixture() -> std::path::PathBuf {
        let root = std::env::temp_dir().join(format!(
            "steam-rule-fixture-{}-{}",
            std::process::id(),
            SEQUENCE.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(root.join("config/lua/Disable")).unwrap();
        root
    }
    #[test]
    fn removes_a_disabled_game_and_all_active_copies() {
        let root = fixture();
        for dir in ["config/lua", "config/lua/Disable", "st_scripts"] {
            fs::create_dir_all(root.join(dir)).unwrap();
            fs::write(root.join(dir).join("990900.lua"), "fixture").unwrap();
        }
        let (removed, failed) = remove_unlocked_rule(&root, 990900).unwrap();
        assert_eq!((removed, failed), (3, 0));
        assert!(!root.join("config/lua/Disable/990900.lua").exists());
        assert_eq!(remove_unlocked_rule(&root, 990900).unwrap(), (0, 0));
    }
    #[test]
    fn clear_includes_disabled_archive_but_preserves_foreign_rules() {
        let root = fixture();
        let disabled = root.join("config/lua/Disable");
        fs::write(
            disabled.join("990900.lua"),
            "-- Generated by 春风渡\nfixture()",
        )
        .unwrap();
        fs::write(
            disabled.join("foreign.lua"),
            "-- third-party rule\nfixture()",
        )
        .unwrap();
        fs::write(
            root.join("config/lua/990901.lua"),
            "-- Generated by 春风渡\nfixture()",
        )
        .unwrap();
        let result = clear_all_rules(&root).unwrap();
        assert_eq!((result.removed, result.failed, result.skipped), (2, 0, 1));
        assert!(!disabled.join("990900.lua").exists());
        assert!(disabled.join("foreign.lua").exists());
    }
}
